services:
  - type: web
    name: sgp-aneel-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node dist/src/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
